version: '3.1'

services:
  
  app:
    build: 
      context: ./app
    image: assorium/js-cdn-images
    restart: always
    ports:
      - ${APP_PORT}:3000
    volumes:
      - ${UPLOAD_PATH_HOST}:/home/node/app/upload
    networks:
      - app-network

  webserver:
    image: nginx
    depends_on:
      - app
    container_name: webserver
    restart: unless-stopped
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - APP_PORT=${APP_PORT}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.template:/etc/nginx/conf.d/default.template
    networks:
      - app-network
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"


networks:
  app-network:
    driver: bridge